version: 2
jobs:
  validate_terraform:
    environment:
      AWS_DEFAULT_REGION: us-east-1
    docker:
      - image: hashicorp/terraform:light
    steps:
      - checkout
      - run:
          name: Install curl
          command: apk add --update curl && apk upgrade
      - run:
          name: terraform init
          command: find . -type f -name "*.tf" -exec dirname {} \;|sort -u | while read m; do (cd "$m" && terraform init -input=false -backend=false) || exit 1; done
      - run:
          name: Validate Terraform configurations
          command: find . -name ".terraform" -prune -o -type f -name "*.tf" -exec dirname {} \;|sort -u | while read m; do (cd "$m" && terraform validate && echo "√ $m") || exit 1 ; done
      - run:
          name: Check if Terraform configurations are properly formatted
          command: if [[ -n "$(terraform fmt -write=false)" ]]; then echo "Some terraform files need be formatted, run 'terraform fmt' to fix"; exit 1; fi
      - run:
          name: Install tflint
          command: curl -L -o /tmp/tflint.zip https://github.com/terraform-linters/tflint/releases/download/v0.13.2/tflint_linux_amd64.zip && unzip /tmp/tflint.zip -d /usr/local/bin
      - run:
          name: Check Terraform configurations with tflint
          command: find . -name ".terraform" -prune -o -type f -name "*.tf" -exec dirname {} \;|sort -u | while read m; do (cd "$m" && tflint && echo "√ $m") || exit 1 ; done
      - run:
          name: install docker-compose
          command: |
            apk add py-pip
            apk add python-dev
            apk add libffi-dev
            apk add openssl-dev
            apk add gcc
            apk add libc-dev
            apk add make
            curl -L "https://github.com/docker/compose/releases/download/1.25.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose
            which docker-compose
            apk add file
            file /usr/local/bin/docker-compose
            cat /etc/os-release
            docker-compose run test
            docker-compose up -d
      - run:
          name: verify localstack
          command: curl http://localhost:8055/
  lint_handler:
    environment:
      AWS_DEFAULT_REGION: us-east-1
    docker:
      - image: circleci/golang:latest
    working_directory: /go/src/github.com/GSA/grace-inventory
    steps:
      - checkout
      - run:
          name: Lint Handler
          command: make lint_handler
  test_handler:
    docker:
      - image: circleci/golang:latest
    working_directory: /go/src/github.com/GSA/grace-inventory
    steps:
      - checkout
      - run:
          name: Run Unit Tests
          command: make test_handler
  release_handler:
    docker:
      - image: circleci/golang:latest
    working_directory: /go/src/github.com/GSA/grace-inventory
    steps:
      - checkout
      - run:
          name: Release handler
          command: make release_handler

workflows:
  version: 2
  build:
    jobs:
      - validate_terraform
      - lint_handler
      - test_handler
      - release_handler:
          filters:
            tags:
              only: /^v.*/
            branches:
              only: master
